### PR TITLE
Fixed Nimbus dark mode open/close icon issue

### PR DESCRIPTION
**Pull request by wayne-zhang**

### CODE REVIEW

**Comment by wayne-zhang** [comment]
Fixed tree open/close icon issue in Nimbus dark mode, which caused by refactoring. Nimbus default tree open/close icon works in light mode only. 

Please review.

image

**Comment by wayne-zhang** [comment]
By the way, do Swing component tree refresh when change to dark mode so that it takes effect without Squirrel SQL restart.

**Comment by gerdwagner** [comment]
Thanks for your pull request. Sorry I still need some time to respond. But I'll certainly come back to you on it.

**Comment by gerdwagner** [comment]
Is merged and will be available in future snapshots and version. Thanks again for the pull request.

**Comment by wayne-zhang** [comment]
Thanks @gerdwagner! I will test the latest snapshot.

**Comment by wayne-zhang** [comment]
All good. Works as expected in snapshot snapshot-20230925_2046.

**Pull request closed without merging**
